version: 0.0.1
achievements:
- achievement:
    name: Participation Badge
    icon: https://
    description: Participated in HacktoberFest'24 GDG GEU x Vaunt
    triggers:
    - trigger:
        actor: author
        action: pull_request
        condition: merged = true & labels in ['participation-eligible']
- achievement:
    name: Active Coontributor
    icon: https://
    description: Succesfully merged 5 PRS in HacktoberFest'24 GDG GEU x Vaunt
    triggers:
    - trigger:
        actor: author
        action: pull_request
        condition: merged = true & labels in ['active-eligible']
- achievement:
    name: Master Contributor
    icon: https://
    description: Succesfully merged 10 PRS in HacktoberFest'24 GDG GEU x Vaunt
    triggers:
    - trigger:
        actor: author
        action: pull_request
        condition: merged = true & labels in ['master-eligible']
