version: 0.0.1
achievements:
  - achievement:
      name: Participation Badge
      icon: https://raw.githubusercontent.com/iamAyushChamoli/hacktoberfest-24/main/.vaunt/badges/participation-badge.png
      description: Participated in HacktoberFest'24 GDG GEU x Vaunt
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: merged = true & labels in ['participation-eligible']
  - achievement:
      name: Active Contributor
      icon: https://raw.githubusercontent.com/iamAyushChamoli/hacktoberfest-24//main/.vaunt/badges/active-badge.png
      description: Successfully merged 5 PRS in HacktoberFest'24 GDG GEU x Vaunt
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: merged = true & labels in ['active-eligible']
  - achievement:
      name: Master Contributor
      icon: https://raw.githubusercontent.com/iamAyushChamoli/hacktoberfest-24//main/.vaunt/badges/master-badge.png
      description: Successfully merged 10 PRS in HacktoberFest'24 GDG GEU x Vaunt
      triggers:
        - trigger:
            actor: author
            action: pull_request
            condition: merged = true & labels in ['master-eligible']
